[project]
# List of environment variables to be provided by each user to use the app.
user_env = []

# Duration (in seconds) during which the session is saved when the connection is lost
session_timeout = 3600

# Duration (in seconds) of the user session expiry
user_session_timeout = 1296000  # 15 days

# Enable third parties caching (e.g., LangChain cache)
cache = false

# Whether to persist user environment variables (API keys) to the database
persist_user_env = false

# Whether to mask user environment variables (API keys) in the UI with password type
mask_user_env = false

# Authorized origins
allow_origins = ["*"]

[features]
# Process and display HTML in messages
unsafe_allow_html = false

# Process and display mathematical expressions
latex = false

# Autoscroll new user messages at the top of the window
user_message_autoscroll = true

# Autoscroll new assistant messages
assistant_message_autoscroll = true

# Automatically tag threads with the current chat profile
auto_tag_thread = true

# Allow users to edit their own messages
edit_message = true

# Allow users to share threads
allow_thread_sharing = false

# Enable favorite messages
favorites = false

[features.slack]

[features.teams]

[UI]
# Name of the app and chatbot
name = "Pet Store Admin"

# Show the readme as a modal on first visit
show_readme_as_default = true

# Description of the app
description = "Administrative console for managing Pet Store products and orders"

# Large size content are by default collapsed for a cleaner UI
default_collapse_content = true

# Hide the chain of thought panel
hide_cot = false

# Link to your github repo
github = ""

# Specify a CSS file that can be used to customize the user interface
custom_css = ""

# Specify a Javascript file that can be run on load
custom_js = ""

# Specify a custom font url
custom_font = ""

# Specify a custom build directory
custom_build = ""

# Override default MUI light theme. (Check theme.ts)
[UI.theme]
default = "light"
layout = "default"
font_family = ""

[UI.theme.light]
background = "#FAFAFA"
paper = "#FFFFFF"

[UI.theme.light.primary]
main = "#0066CC"
dark = "#004C99"
light = "#3399FF"

[UI.theme.light.secondary]

[UI.theme.dark]
background = "#1A1A1A"
paper = "#262626"

[UI.theme.dark.primary]
main = "#3399FF"
dark = "#0066CC"
light = "#66B2FF"

[UI.theme.dark.secondary]

[meta]
generated_by = "1.3.0"
